# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `devise-argon2` gem.
# Please instead update this file by running `bin/tapioca gem devise-argon2`.


# source://devise-argon2//lib/devise-argon2/version.rb#1
module Devise
  # source://devise-argon2//lib/devise-argon2.rb#7
  def argon2_options; end

  # source://devise-argon2//lib/devise-argon2.rb#7
  def argon2_options=(val); end

  class << self
    # source://devise-argon2//lib/devise-argon2.rb#7
    def argon2_options; end

    # source://devise-argon2//lib/devise-argon2.rb#7
    def argon2_options=(val); end
  end
end

# source://devise-argon2//lib/devise-argon2/version.rb#2
module Devise::Argon2; end

# source://devise-argon2//lib/devise-argon2/version.rb#3
Devise::Argon2::ARGON2_VERSION = T.let(T.unsafe(nil), String)

# source://devise-argon2//lib/devise-argon2/model.rb#4
module Devise::Models; end

# source://devise-argon2//lib/devise-argon2/model.rb#5
module Devise::Models::Argon2
  # source://devise-argon2//lib/devise-argon2/model.rb#41
  def password=(new_password); end

  # @return [Boolean]
  #
  # source://devise-argon2//lib/devise-argon2/model.rb#6
  def valid_password?(password); end

  protected

  # source://devise-argon2//lib/devise-argon2/model.rb#48
  def password_digest(password); end

  private

  # source://devise-argon2//lib/devise-argon2/model.rb#86
  def configured_work_factors; end

  # @return [Boolean]
  #
  # source://devise-argon2//lib/devise-argon2/model.rb#106
  def migrate_hash_from_devise_argon2_v1?; end

  # @return [Boolean]
  #
  # source://devise-argon2//lib/devise-argon2/model.rb#76
  def outdated_work_factors?; end

  # source://devise-argon2//lib/devise-argon2/model.rb#57
  def update_hash(password); end

  # source://devise-argon2//lib/devise-argon2/model.rb#68
  def update_without_callbacks(attributes); end
end

# source://devise-argon2//lib/devise-argon2/model.rb#112
module Devise::Models::Argon2::ClassMethods
  # source://devise-argon2//lib/devise-argon2/model.rb#113
  def argon2_options; end

  # source://devise-argon2//lib/devise-argon2/model.rb#113
  def argon2_options=(value); end

  class << self
    # source://devise-argon2//lib/devise-argon2/model.rb#113
    def available_configs; end

    # source://devise-argon2//lib/devise-argon2/model.rb#113
    def available_configs=(_arg0); end
  end
end
