# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OrganizationSerializer`.
# Please instead update this file by running `bin/tapioca dsl OrganizationSerializer`.


class OrganizationSerializer
  sig { returns(Organization) }
  def organization; end
end
