# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ProjectSerializer`.
# Please instead update this file by running `bin/tapioca dsl ProjectSerializer`.


class ProjectSerializer
  sig { returns(Project) }
  def project; end
end
