# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ReporterSerializer`.
# Please instead update this file by running `bin/tapioca dsl ReporterSerializer`.


class ReporterSerializer
  sig { returns(Reporter) }
  def reporter; end
end
