# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SchemaSnapshotSerializer`.
# Please instead update this file by running `bin/tapioca dsl SchemaSnapshotSerializer`.


class SchemaSnapshotSerializer
  sig { returns(SchemaSnapshot) }
  def schema_snapshot; end
end
